wandb_version: 1

system_metrics:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725375736
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 83
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 83
      3:
      - 13
      - 16
      - 23
      4: 3.10.14
      5: 0.17.8
      6: 4.44.2
      8:
      - 5
      13: linux-x86_64
